import { Bricolage_Grotesque } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Script from "next/script";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL('https://www.nextappsinc.com'),
  alternates: {
    canonical: './',
  },
  title: "Create Next Apps",
  description: "Generated by create next apps",

  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "none",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bricolageGrotesque.className} antialiased`}>
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17899557039"
          strategy="afterInteractive"
        />

        <Script id="google-ads" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17899557039');
          `}
        </Script>

        <Header />
        {children}
        <Footer />
        {/* Start of Chat Script */}
        <Script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=4338bf84-3cf8-46ef-9cd1-996399dc7b9d" strategy="afterInteractive" />
        <Script id="zopim-init" strategy="afterInteractive">
          {`
            window.$zopim || function (a, d) {
                var b = $zopim = function (a) {
                        b._.push(a)
                    },
                    c = b.s = a.createElement(d);
                a = a.getElementsByTagName(d)[0];
                b.set = function (a) {
                    b.set._.push(a)
                };
                b._ = [];
                b.set._ = [];
                c.async = !0;
                c.setAttribute("charset", "utf-8");
                c.src = "";
                b.t = +new Date;
                c.type = "text/javascript";
                a.parentNode.insertBefore(c, a)
            }(document, "script");

            $zopim(function () {
                function a(a) {
                    1 <= a && $zopim.livechat.window.show()
                }
                $zopim.livechat.setOnUnreadMsgs(a)
            });

            function setButtonURL() {
                $zopim.livechat.window.show();
            }

            function toggleChat() {
                if (window.$zopim && window.$zopim.livechat && window.$zopim.livechat.window) {
                    $zopim.livechat.window.toggle();
                }
            }

            // Global click handler for elements with 'chat' or 'chats' class
            document.addEventListener('click', function(e) {
                if (e.target.closest('.chat') || e.target.closest('.chats')) {
                    e.preventDefault();
                    toggleChat();
                }
            });
          `}
        </Script>
        {/* End of Chat Script */}
      </body>
    </html>
  );
}
