import { Bricolage_Grotesque } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Script from "next/script";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata = {
  metadataBase: new URL('https://www.nextappsinc.com'),
  alternates: {
    canonical: './',
  },
  title: "Create Next App",
  description: "Generated by create next app",

  robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "none",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bricolageGrotesque.className} antialiased`}>
        <Header />
        {children}
        <Footer />

        {/* Google Analytics */}
        <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=AW-17899557039`}
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17899557039');
          `}
        </Script>

        {/* Start of Chat Script */}
        <Script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=4338bf84-3cf8-46ef-9cd1-996399dc7b9d" strategy="afterInteractive" />
        <Script id="zopim-init" strategy="afterInteractive">
          {`
            window.$zopim || (function(d, s) {
              var z = $zopim = function(c) { z._.push(c) },
                  $ = z.s = d.createElement(s),
                  e = d.getElementsByTagName(s)[0];
              z.set = function(o) { z.set._.push(o) };
              z._ = [];
              z.set._ = [];
              $.async = !0;
              $.setAttribute("charset", "utf-8");
              $.src = "https://v2.zopim.com/?4338bf84-3cf8-46ef-9cd1-996399dc7b9d";
              z.t = +new Date;
              $.type = "text/javascript";
              e.parentNode.insertBefore($, e);
            })(document, "script");

            $zopim(function() {
              function a(a) {
                1 <= a && $zopim.livechat.window.show()
              }
              $zopim.livechat.setOnUnreadMsgs(a)
            });

            function setButtonURL() {
              $zopim.livechat.window.show();
            }

            function toggleChat(e) {
              if (e) e.preventDefault();
              if (window.$zopim && window.$zopim.livechat && window.$zopim.livechat.window) {
                window.$zopim.livechat.window.toggle();
              }
              return false;
            }

            // Global click handler for elements with 'chat' class
            document.addEventListener('click', function(e) {
              if (e.target.closest('.chat')) {
                e.preventDefault();
                toggleChat();
              }
            });
          `}
        </Script>
        {/* End of Chat Script */}
      </body>
    </html>
  );
}
